#!/bin/bash
#instructions are for ubuntu 18.04
##CAUTION: this file is for a clean install of Ubuntu.  If you have messed with your environment, 
#run everything with sudo apt remove [apps], then sudo apt autoremove, then run this script

#update apt
sudo apt-get update
sudo apt-get upgrade

#install git
sudo apt-get install git

#install jre
sudo apt install default-jre

#install maven
sudo apt install maven

#****these commands are needed for compiling
sudo apt install default-jdk            
sudo apt install openjdk-11-jdk-headless
sudo apt install ecj                    
sudo apt install openjdk-8-jdk-headless
#*****
